#refrence document https://docs.ansible.com/ansible/2.8/modules/apt_module.html?highlight=apt
#beauty of playbook ---> you dont need to write the -y , sudo install and blah blah :p
-
  name: Install Docker
  hosts: servers
  become: yes
  tasks:
    - name: install docker based on server distribution
      apt:
        name: docker.io
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install the latest version of docker based on distribution
      dnf:
        name: docker
        state: latest
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'Redhat'
