-
  name: website deployment
  become: yes
  hosts: servers

  tasks:
   - name: Install nginx and Deploy website using nginx
     apt:
       name: nginx
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: start nginx
     service:
       name: nginx
       state: started
       enabled: yes
     when: ansible_distribution == "Ubuntu"
#-------------------#
   - name: Install httpd and Deploy website using Apache HTTPD
     dnf:
       name: httpd
       state: latest
     when: ansible_distribution == "Amazon" or ansible_distribution == "RedHat"

   - name: start httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "Amazon" or ansible_distribution == "RedHat"
     
#scp -i .\n.virginia-key.pem -r C:\Users\dci-student\Downloads\carvilla-v1.0\ ubuntu@18.205.21.13:/home/ubuntu/
   - name: copy website files to server destination
     copy:
       src: /home/ubuntu/carvilla-v1.0/
       dest: /var/www/html/
